version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elastic-search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    ports:
      - "9200:9200"
    networks:
      - elk
    volumes:
      - es_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  kotlin-app:
    build:
      context: .
    container_name: github-analyzer
    environment:
      - PORT=${PORT}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - elasticsearch
    ports:
      - "${PORT}:${PORT}"

volumes:
  es_data:
    driver: local
networks:
  elk:
    driver: bridge